log4j.rootLogger=DEBUG, STDOUT, FILE
log4j.logger.deng=DEBUG
log4j.logger.org.terasology.gestalt.module.sandbox.PermissionSet=ERROR
log4j.logger.org.terasology.reflection.copy.CopyStrategyLibrary=ERROR
log4j.logger.org.terasology.gestalt.entitysystem.event.impl.EventReceiverMethodSupport=ERROR
log4j.logger.org.reflections=ERROR

log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%d{HH:mm:ss.SSS} %5p [%t] (%F:%L) - %m%n

log4j.appender.FILE=org.apache.log4j.RollingFileAppender
log4j.appender.FILE.File=destinationsol.log
log4j.appender.FILE.MaxFileSize=10MB
log4j.appender.FILE.MaxBackupIndex=3
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] (%F:%L) - %m%n
log4j.appender.FILE.threshold=DEBUG
