// Copyright 2026 The Destination Sol contributors
// SPDX-License-Identifier: Apache-2.0
package org.destinationsol.modules.vfx.components;

import org.terasology.gestalt.entitysystem.component.Component;

// Describes a lightning effect to be generated by LightningPath and drawn by
// VectorEffectsDrawer. Carried by a weapon, arc emitter, or shield strike.
// seekMetal turns on the fork-chases-nearest-metal behavior (wire a
// MetalLocator backed by the Material component to make it real).
public class LightningBolt implements Component<LightningBolt> {

    public float segmentLength = 0.3f;
    public float angleToleranceDeg = 30f;
    public float curlDeg = 0f;
    public int maxForkDepth = 3;
    public float width = 0.1f;
    public float lifetime = 0.15f;
    public String tint = "white";
    public boolean seekMetal = true;

    @Override
    public void copyFrom(LightningBolt other) {
        this.segmentLength = other.segmentLength;
        this.angleToleranceDeg = other.angleToleranceDeg;
        this.curlDeg = other.curlDeg;
        this.maxForkDepth = other.maxForkDepth;
        this.width = other.width;
        this.lifetime = other.lifetime;
        this.tint = other.tint;
        this.seekMetal = other.seekMetal;
    }
}
